Хабутдинов Арслан
mipt-diht/mipt-latex-fall2018-Khabutdinov-Arslan pull request #1
Opened 2018-10-19 06:06 UTC by Khabutdinov-Arslan

Первая версия первой домашки

2018-10-19 18:49 UTC, AShepelevv requested changes

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	{
Давайте не будем делать как в плюсах. Содержимое области видимости можно начинать в той же строке, где и открывающая скобка.

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	}
Если пишем так, то не забываем о табуляции. Но "аргумент" не очень большой, в принципе это не важно, можно все писать в одну строчку.

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	А теперь формулы. \textsc{Формула} --- краткое и точное словесное выражение, определение или же ряд математических величин, выраженный условными знаками.
Перед тире нужно ставить неразрывный пробел (см. лекцию).

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	\hspace{14pt}
Горизонтальный отступ лучше писать в той же строчке, что и последующий текст.

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	\end{center}
Перед концом окружения оставлять пустые строчки смысла нет, потому что конец окружения все равно их съест.

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	\vspace{0.5776cm}
Что за подгон????

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	\tan{\frac{\alpha}{2}} = \sqrt{\frac{(p-b)(p-c)}{p(p-a)}},
В исходной pdf `\tg`, а не `\tan`. А еще не плохо ставить пробелы в формулах, хотя бы для логического разделения содержимого.

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	\end{flushleft}
Зачем выравнивая по левому краю?

2018-10-19 18:49 UTC, AShepelevv commented on task1.tex
> +	\Large
Писать переключатели в отдельных строках слишком жирно, можно все и на одной.

2018-10-19 18:56 UTC, AShepelevv commented on task1.tex
> +	}
Из-за того, что у тебя закрывающая скобка на новой строчке (а должна быть вплотную к тексту) в pdf вторая строчка эпиграфа не прижата к правому краю (сравни с запятой).

2018-10-19 19:18 UTC, Khabutdinov-Arslan commented on task1.tex
> +	\vspace{0.5776cm}
Что за неуказанный вертикальный отступ перед "Ура!!!"?

2018-10-19 19:50 UTC, Khabutdinov-Arslan commented
Fixes?

2018-10-21 16:31 UTC, Khabutdinov-Arslan commented on task1.tex
> +	\end{center}
fixed?

2018-10-21 17:08 UTC, AShepelevv requested changes

2018-10-21 17:08 UTC, AShepelevv commented on task1.tex
> +	\end{center}
Зачем тут `\vspace`? Почему 

```
{\Huge \sffamily 
<<Ура!!!>>}
```

растянуто на 2 строчки? Где отступы?

2018-10-21 17:08 UTC, AShepelevv commented on task1.tex
>  	Это мой первый документ в системе компьютерной вёрстки \LaTeX.
Где отступы?

2018-10-21 17:08 UTC, AShepelevv commented on task1.tex
> +	a ^ 2 = b ^ 2 - 2bc \cos{\alpha},
А вот индексы лучше не отделять пробелами, чтобы они не потерялись

2018-10-21 17:08 UTC, AShepelevv commented on task1.tex
>  	На сегодня, пожалуй, хватит\dots Удачи!
В примере нет абзацного отступа. А у тебя есть (см. pdf)

2018-10-21 17:22 UTC, AShepelevv commented
Принято)

2018-10-21 17:23 UTC, merged