Хабутдинов Арслан
mipt-diht/mipt-latex-fall2018-Khabutdinov-Arslan pull request #6
Opened 2018-10-28 10:47 UTC by Khabutdinov-Arslan

Пересоздал ветку, чтобы решить конфликты

2018-10-30 15:54 UTC, AShepelevv requested changes

2018-10-30 15:54 UTC, AShepelevv commented on task2.tex
> +        Случайный вектор $\vec \xi$~--- гаусс, если  $\forall \lambda \in \mathbb{R}^n$ случайная величина,$\biggl(\vec\lambda, \vec\xi\biggr)$ имеем нормальное распределение.
Слишком огромные скобочки.

2018-10-30 15:54 UTC, AShepelevv commented on task2.tex
> +        Установите астрономический азимут восхода звезды $\varepsilon$ CМa ($6^h58^m38^s$, $-28^\circ58'$) при наблюдении из самой северной равноудалённой от Санкт-Петербурга ($59^\circ57'$ с.ш., $30
Угловые минуты пишутся без степени, то есть Просто `20'`.
Между градусами и минутами и между минутами и секундами ставится половинный пробел.
`h`, `m`, `s` – наименования, то есть текст. Значит и писать тх нужно внутри `\text{}`.

2018-10-30 15:54 UTC, AShepelevv commented on task2.tex
> +        В какой момент по истинному солнечному времени 1 сентября Регул ($\alpha_1 = 10^h9^m$, $\delta_1 = 11^\circ53'$) и Шератан ($\alpha_2 = 11^h15^m$, $\delta_2 = 15^\circ20'$) находятся на одном
Угловые минуты пишутся без степени, то есть Просто `20'`.
Между градусами и минутами и между минутами и секундами ставится половинный пробел.
`h`, `m`, `s` – наименования, то есть текст. Значит и писать тх нужно внутри `\text{}`.

2018-10-30 15:54 UTC, AShepelevv commented on task2.tex
> +        Установите астрономический азимут восхода звезды $\varepsilon$ CМa ($6^h58^m38^s$, $-28^\circ58'$) при наблюдении из самой северной равноудалённой от Санкт-Петербурга ($59^\circ57'$ с.ш., $30
в. д. пишется через половинный пробел, как и с. ш.

2018-10-30 15:54 UTC, AShepelevv commented on task2.tex
> +        Установите астрономический азимут восхода звезды $\varepsilon$ CМa ($6^h58^m38^s$, $-28^\circ58'$) при наблюдении из самой северной равноудалённой от Санкт-Петербурга ($59^\circ57'$ с.ш., $30
А еще их нужно "прикрепить" к величине с помощью неразрывного пробела.

2018-10-30 15:54 UTC, AShepelevv commented on task2.tex
> +        \item[$\bigstar$] Материал увлекательный, 5 \LaTeX ~звезд!
Зачем пробел перед неразрывным пробелом?

2018-10-30 15:54 UTC, AShepelevv commented on task2.tex
> +        Случайный вектор $\vec \xi \sim (m, \Sigma)$ ~--- гаусс, если его характеристическая функция $\varphi_\xi\biggl(\vec t\biggr) = \exp{\biggl(i\biggl(\vec m, \vec t} - \frac{1}{2}\biggl(\Sigma
`Сл. век. \xi~--- гауссовский` мы избавляемся от сокращений.

2018-10-30 15:54 UTC, AShepelevv commented on task2.tex
> +        Пусть $\{\xi_k\}_{k \geq 1}$~--- независимая случайная величина, $\mathsf{E}\xi_k < +\infty$, $\forall k$ обозначим $m_k = \mathsf{E}\xi_k$, $\sigma_k^2 = \mathsf{D}\xi_k > 0:S_n = \sum\limit
В фигурных скобках пишут последовательности, поэтому это все-таки случайте величинЫ.

2018-11-04 17:31 UTC, AShepelevv requested changes

2018-11-04 17:31 UTC, AShepelevv commented on task2.tex
> +        Случайный вектор $\vec \xi \sim (m, \Sigma)$~--- гауссовский, если его характеристическая функция $\varphi_\xi\bigl(\vec t\bigr) = \exp{\bigl(i\bigl(\vec m, \vec t} - \frac{1}{2}\bigl(\Sigma
Скобочная последовательность не является правильной((

Внутренние скобки должны быть меньше внешних, ты их все увеличил зачем-то.

2018-11-04 17:31 UTC, AShepelevv commented on task2.tex
> +        Случайный вектор $\vec \xi \sim (m, \Sigma)$~--- гауссовский, если его характеристическая функция $\varphi_\xi\bigl(\vec t\bigr) = \exp{\bigl(i\bigl(\vec m, \vec t} - \frac{1}{2}\bigl(\Sigma
Посмотри эту ссылку https://tex.stackexchange.com/questions/176165/vector-arrow-running-into-brackets, чтобы было красиво

2018-11-04 19:16 UTC, Khabutdinov-Arslan commented on task2.tex
> +        Случайный вектор $\vec \xi \sim (m, \Sigma)$~--- гауссовский, если его характеристическая функция $\varphi_\xi\bigl(\vec t\bigr) = \exp{\bigl(i\bigl(\vec m, \vec t} - \frac{1}{2}\bigl(\Sigma
Fixed?

2018-11-05 07:21 UTC, AShepelevv commented on task2.tex
> +        Случайный вектор $\vec \xi \sim (m, \Sigma)$~--- гауссовский, если его характеристическая функция $\varphi_\xi\bigl(\vec t\bigr) = \exp{\bigl(i\bigl(\vec m, \vec t} - \frac{1}{2}\bigl(\Sigma
Ага

2018-11-05 07:21 UTC, merged